-- ==============================================
-- 1. TABEL USERS (Admin/Customer Profile)
-- ==============================================
-- Karena menggunakan Neon (PostgreSQL murni), kita tidak lagi terikat 
-- dengan auth bawaan Supabase. Kita membuat tabel user yang independen.
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nama TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL, -- Diperlukan untuk login manual nantinya
  role TEXT DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================
-- 2. TABEL PRODUK
-- ==============================================
CREATE TABLE IF NOT EXISTS produk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_produk TEXT NOT NULL,
  kategori TEXT NOT NULL,
  deskripsi TEXT,
  harga INTEGER NOT NULL,
  image_url TEXT,
  badge TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================
-- 3. TABEL PO BATCH
-- ==============================================
CREATE TABLE IF NOT EXISTS po_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_batch TEXT NOT NULL,
  catatan TEXT,
  status TEXT DEFAULT 'Closed' CHECK (status IN ('Open', 'Closed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================
-- 4. TABEL PESANAN
-- ==============================================
CREATE TABLE IF NOT EXISTS pesanan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL, -- Opsional, NULL untuk Guest Checkout
  produk_id BIGINT REFERENCES produk(id) ON DELETE SET NULL,
  batch_id BIGINT REFERENCES po_batches(id) ON DELETE SET NULL,
  nama_lengkap TEXT NOT NULL,
  no_wa TEXT NOT NULL,
  alamat TEXT NOT NULL,
  produk_nama TEXT NOT NULL,
  produk_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  jumlah INTEGER NOT NULL DEFAULT 1,
  total_harga INTEGER NOT NULL,
  metode_pembayaran TEXT NOT NULL DEFAULT 'cash' CHECK (metode_pembayaran IN ('cash', 'qris')),
  bukti_pembayaran TEXT,
  catatan TEXT,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Diproses', 'Selesai', 'Dibatalkan')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================
-- 5. TABEL FEEDBACKS
-- ==============================================
CREATE TABLE IF NOT EXISTS feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  pesan TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================
-- 6. TABEL APP SETTINGS
-- ==============================================
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================
-- 7. SEEDER (Data Dummy)
-- ==============================================

-- 1. Seeder Admin (Password dummy, idealnya BCrypt Hash. Untuk test dibuat plain dulu atau hash tertentu)
INSERT INTO users (nama, email, password_hash, role) 
VALUES ('Admin MoriBites', 'admin@moribites.id', 'hashed_password_disini', 'admin')
ON CONFLICT (email) DO NOTHING;

-- 1b. Seeder Pengaturan
INSERT INTO app_settings (key, value)
VALUES ('order_open', 'true'::jsonb)
ON CONFLICT (key) DO NOTHING;

INSERT INTO app_settings (key, value)
VALUES ('active_batch_id', 'null'::jsonb)
ON CONFLICT (key) DO NOTHING;

ALTER TABLE pesanan
ADD COLUMN IF NOT EXISTS metode_pembayaran TEXT NOT NULL DEFAULT 'cash',
ADD COLUMN IF NOT EXISTS bukti_pembayaran TEXT,
ADD COLUMN IF NOT EXISTS produk_items JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE pesanan
DROP CONSTRAINT IF EXISTS pesanan_metode_pembayaran_check;

ALTER TABLE pesanan
ADD CONSTRAINT pesanan_metode_pembayaran_check CHECK (metode_pembayaran IN ('cash', 'qris'));

-- 1c. Seeder Batch
INSERT INTO po_batches (nama_batch, catatan, status)
SELECT 'Batch 1', 'Batch awal pemesanan MoriBites.', 'Open'
WHERE NOT EXISTS (SELECT 1 FROM po_batches);

-- 2. Seeder Produk
INSERT INTO produk (nama_produk, kategori, deskripsi, harga, image_url, badge)
VALUES
  ('Produk Unggulan Alpha', 'Kategori A', 'Deskripsi singkat produk ini.', 150000, '/img/produk1.jpg', 'Terlaris'),
  ('Produk Premium Beta', 'Kategori B', 'Varian premium.', 220000, '/img/produk2.jpg', NULL),
  ('Paket Hemat Zeta', 'Paket Bundling', 'Beli lebih, hemat lebih.', 450000, '/img/produk6.jpg', 'Terlaris');

-- 3. Seeder Pesanan
INSERT INTO pesanan (produk_id, nama_lengkap, no_wa, alamat, produk_nama, jumlah, total_harga, catatan, status)
VALUES
  (1, 'Budi Santoso', '081234567890', 'Jember', 'Produk Unggulan Alpha', 2, 300000, 'Pengiriman sore', 'Pending'),
  (3, 'Siti Aminah', '085566778899', 'Banyuwangi', 'Paket Hemat Zeta', 1, 450000, 'Titip pos', 'Diproses');

-- 4. Seeder Feedback
INSERT INTO feedbacks (nama, pesan, rating)
VALUES
  ('Budi', 'Cookies sangat enak.', 5),
  ('Aminah', 'Varian Zeta sangat memuaskan.', 4);
