import pg from 'pg'

const { Pool } = pg

let pool: pg.Pool | undefined
let schemaReady: Promise<void> | undefined

export function useDb() {
  if (!pool) {
    const databaseUrl = process.env.DATABASE_URL
    if (!databaseUrl) {
      throw createError({
        statusCode: 500,
        statusMessage: 'DATABASE_URL belum dikonfigurasi.'
      })
    }

    pool = new Pool({
      connectionString: databaseUrl,
      ssl: { rejectUnauthorized: false }
    })
  }

  return pool
}

export async function query<T = any>(text: string, params: unknown[] = []) {
  await ensureDatabase()
  return useDb().query<T>(text, params)
}

export async function ensureDatabase() {
  if (!schemaReady) {
    schemaReady = setupDatabase()
  }

  return schemaReady
}

async function setupDatabase() {
  const db = useDb()

  await db.query(`
    CREATE TABLE IF NOT EXISTS users (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      nama TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      role TEXT DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS produk (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nama_produk TEXT NOT NULL,
      kategori TEXT NOT NULL,
      deskripsi TEXT,
      harga INTEGER NOT NULL,
      image_url TEXT,
      badge TEXT,
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS po_batches (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nama_batch TEXT NOT NULL,
      catatan TEXT,
      status TEXT DEFAULT 'Closed' CHECK (status IN ('Open', 'Closed')),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS pesanan (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id UUID REFERENCES users(id) ON DELETE SET NULL,
      produk_id BIGINT REFERENCES produk(id) ON DELETE SET NULL,
      batch_id BIGINT REFERENCES po_batches(id) ON DELETE SET NULL,
      nama_lengkap TEXT NOT NULL,
      no_wa TEXT NOT NULL,
      alamat TEXT NOT NULL,
      produk_nama TEXT NOT NULL,
      jumlah INTEGER NOT NULL DEFAULT 1,
      total_harga INTEGER NOT NULL,
      metode_pembayaran TEXT NOT NULL DEFAULT 'cash' CHECK (metode_pembayaran IN ('cash', 'qris')),
      bukti_pembayaran TEXT,
      catatan TEXT,
      status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Diproses', 'Selesai', 'Dibatalkan')),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS feedbacks (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nama TEXT NOT NULL,
      pesan TEXT NOT NULL,
      rating INTEGER CHECK (rating >= 1 AND rating <= 5),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS app_settings (
      key TEXT PRIMARY KEY,
      value JSONB NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    );
  `)

  await db.query(`
    ALTER TABLE pesanan
    ADD COLUMN IF NOT EXISTS batch_id BIGINT REFERENCES po_batches(id) ON DELETE SET NULL;
  `)

  await db.query(`
    ALTER TABLE pesanan
    ADD COLUMN IF NOT EXISTS metode_pembayaran TEXT NOT NULL DEFAULT 'cash',
    ADD COLUMN IF NOT EXISTS bukti_pembayaran TEXT;

    ALTER TABLE pesanan
    DROP CONSTRAINT IF EXISTS pesanan_metode_pembayaran_check;

    ALTER TABLE pesanan
    ADD CONSTRAINT pesanan_metode_pembayaran_check CHECK (metode_pembayaran IN ('cash', 'qris'));
  `)

  await db.query(`
    INSERT INTO app_settings (key, value)
    VALUES ('order_open', 'true'::jsonb)
    ON CONFLICT (key) DO NOTHING;

    INSERT INTO app_settings (key, value)
    VALUES ('active_batch_id', 'null'::jsonb)
    ON CONFLICT (key) DO NOTHING;
  `)

  const batches = await db.query<{ count: string }>('SELECT COUNT(*)::text AS count FROM po_batches')
  if (Number(batches.rows[0]?.count || 0) === 0) {
    const createdBatch = await db.query(`
      INSERT INTO po_batches (nama_batch, catatan, status)
      VALUES ('Batch 1', 'Batch awal pemesanan MoriBites.', 'Open')
      RETURNING id
    `)

    await db.query(`
      UPDATE app_settings
      SET value = $1::jsonb, updated_at = CURRENT_TIMESTAMP
      WHERE key = 'active_batch_id'
    `, [JSON.stringify(String(createdBatch.rows[0].id))])
  }

  const products = await db.query<{ count: string }>('SELECT COUNT(*)::text AS count FROM produk')
  if (Number(products.rows[0]?.count || 0) === 0) {
    await db.query(`
      INSERT INTO produk (nama_produk, kategori, deskripsi, harga, image_url, badge, is_active)
      VALUES
        ('Produk Unggulan Alpha', 'Kategori A', 'Deskripsi singkat produk ini. Dibuat dengan bahan pilihan, nyaman untuk camilan harian.', 150000, '', 'Terlaris', TRUE),
        ('Produk Premium Beta', 'Kategori B', 'Varian premium dengan rasa lebih kaya. Cocok untuk kamu yang menginginkan yang terbaik.', 220000, '', NULL, TRUE),
        ('Produk Natural Gamma', 'Kategori C', 'Rasa natural dengan komposisi yang ringan untuk teman aktivitas.', 180000, '', 'Baru', TRUE),
        ('Produk Spesial Delta', 'Kategori D', 'Edisi spesial untuk pesanan terbatas dengan rasa yang lebih berani.', 295000, '', 'Hot', TRUE),
        ('Produk Exclusive Epsilon', 'Kategori E', 'Formulasi eksklusif yang hanya tersedia di MoriBites.', 350000, '', NULL, TRUE),
        ('Paket Hemat Zeta', 'Paket Bundling', 'Beli lebih, hemat lebih. Cocok untuk keluarga atau hadiah.', 450000, '', NULL, TRUE);
    `)
  }
}

export function mapProduct(row: any) {
  return {
    id: String(row.id),
    name: row.nama_produk,
    category: row.kategori,
    description: row.deskripsi || '',
    price: Number(row.harga || 0),
    image: row.image_url || '',
    badge: row.badge || '',
    active: Boolean(row.is_active)
  }
}

export function mapOrder(row: any) {
  return {
    id: String(row.id),
    batchId: row.batch_id ? String(row.batch_id) : '',
    batchName: row.nama_batch || 'Tanpa Batch',
    nama: row.nama_lengkap,
    wa: row.no_wa,
    alamat: row.alamat,
    produkId: row.produk_id ? String(row.produk_id) : '',
    produk: row.produk_nama,
    harga: Number(row.jumlah || 0) > 0 ? Math.floor(Number(row.total_harga || 0) / Number(row.jumlah)) : 0,
    qty: Number(row.jumlah || 1),
    total: Number(row.total_harga || 0),
    metodePembayaran: row.metode_pembayaran || 'cash',
    buktiPembayaran: row.bukti_pembayaran || '',
    catatan: row.catatan || '',
    status: row.status,
    waktu: row.created_at
  }
}

export function mapBatch(row: any) {
  return {
    id: String(row.id),
    name: row.nama_batch,
    note: row.catatan || '',
    status: row.status,
    createdAt: row.created_at
  }
}
